/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppEvidenceRouteImport } from './routes/_app.evidence'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppRulebookRouteImport } from './routes/_app.rulebook'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppShadowRouteImport } from './routes/_app.shadow'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppVersionsIdRouteImport } from './routes/_app.versions.$id'
import { Route as AppCampaignsIdIndexRouteImport } from './routes/_app.campaigns.$id.index'
import { Route as AppCampaignsIdVersionsNewRouteImport } from './routes/_app.campaigns.$id.versions.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRulebookRoute = AppRulebookRouteImport.update({
  id: '/rulebook',
  path: '/rulebook',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShadowRoute = AppShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppVersionsIdRoute = AppVersionsIdRouteImport.update({
  id: '/versions/$id',
  path: '/versions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdIndexRoute = AppCampaignsIdIndexRouteImport.update({
  id: '/campaigns/$id/',
  path: '/campaigns/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdVersionsNewRoute =
  AppCampaignsIdVersionsNewRouteImport.update({
    id: '/campaigns/$id/versions/new',
    path: '/campaigns/$id/versions/new',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/evidence': typeof AppEvidenceRoute
  '/review': typeof AppReviewRoute
  '/rulebook': typeof AppRulebookRoute
  '/settings': typeof AppSettingsRoute
  '/shadow': typeof AppShadowRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/versions/$id': typeof AppVersionsIdRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/campaigns/$id/': typeof AppCampaignsIdIndexRoute
  '/campaigns/$id/versions/new': typeof AppCampaignsIdVersionsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/evidence': typeof AppEvidenceRoute
  '/review': typeof AppReviewRoute
  '/rulebook': typeof AppRulebookRoute
  '/settings': typeof AppSettingsRoute
  '/shadow': typeof AppShadowRoute
  '/': typeof AppIndexRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/versions/$id': typeof AppVersionsIdRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/campaigns/$id': typeof AppCampaignsIdIndexRoute
  '/campaigns/$id/versions/new': typeof AppCampaignsIdVersionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/evidence': typeof AppEvidenceRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/rulebook': typeof AppRulebookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shadow': typeof AppShadowRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/versions/$id': typeof AppVersionsIdRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/campaigns/$id/': typeof AppCampaignsIdIndexRoute
  '/_app/campaigns/$id/versions/new': typeof AppCampaignsIdVersionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/evidence'
    | '/review'
    | '/rulebook'
    | '/settings'
    | '/shadow'
    | '/campaigns/new'
    | '/versions/$id'
    | '/campaigns/'
    | '/campaigns/$id/'
    | '/campaigns/$id/versions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/evidence'
    | '/review'
    | '/rulebook'
    | '/settings'
    | '/shadow'
    | '/'
    | '/campaigns/new'
    | '/versions/$id'
    | '/campaigns'
    | '/campaigns/$id'
    | '/campaigns/$id/versions/new'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/evidence'
    | '/_app/review'
    | '/_app/rulebook'
    | '/_app/settings'
    | '/_app/shadow'
    | '/_app/'
    | '/_app/campaigns/new'
    | '/_app/versions/$id'
    | '/_app/campaigns/'
    | '/_app/campaigns/$id/'
    | '/_app/campaigns/$id/versions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence': {
      id: '/_app/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rulebook': {
      id: '/_app/rulebook'
      path: '/rulebook'
      fullPath: '/rulebook'
      preLoaderRoute: typeof AppRulebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shadow': {
      id: '/_app/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof AppShadowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/versions/$id': {
      id: '/_app/versions/$id'
      path: '/versions/$id'
      fullPath: '/versions/$id'
      preLoaderRoute: typeof AppVersionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id/': {
      id: '/_app/campaigns/$id/'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id/'
      preLoaderRoute: typeof AppCampaignsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id/versions/new': {
      id: '/_app/campaigns/$id/versions/new'
      path: '/campaigns/$id/versions/new'
      fullPath: '/campaigns/$id/versions/new'
      preLoaderRoute: typeof AppCampaignsIdVersionsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppReviewRoute: typeof AppReviewRoute
  AppRulebookRoute: typeof AppRulebookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShadowRoute: typeof AppShadowRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppVersionsIdRoute: typeof AppVersionsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppCampaignsIdIndexRoute: typeof AppCampaignsIdIndexRoute
  AppCampaignsIdVersionsNewRoute: typeof AppCampaignsIdVersionsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEvidenceRoute: AppEvidenceRoute,
  AppReviewRoute: AppReviewRoute,
  AppRulebookRoute: AppRulebookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShadowRoute: AppShadowRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppVersionsIdRoute: AppVersionsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppCampaignsIdIndexRoute: AppCampaignsIdIndexRoute,
  AppCampaignsIdVersionsNewRoute: AppCampaignsIdVersionsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
