/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginBodyInput"];
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": null;
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": null;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    mode?: "live" | "shadow";
                    q?: string;
                    state?: "draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["CampaignListItem"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCampaignBodyInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignDetail"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateVersionBodyInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateVersionResponse"];
                    };
                };
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateVersionResponse"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationDetail"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            affectedCount: number;
                            affectedRowsTruncated: boolean;
                            affectedSample: string[];
                            /** @enum {string} */
                            category: "timing" | "consent" | "audience" | "content" | "identity" | "delivery";
                            citation: components["schemas"]["Citation"];
                            decisions: components["schemas"]["Decision"][];
                            /** Format: uuid */
                            evaluationId: string;
                            explanation: string;
                            /** Format: uuid */
                            id: string;
                            ruleId: string;
                            /** @enum {string} */
                            severity: "block" | "warn" | "info";
                            suggestedFix: components["schemas"]["SuggestedFix"] | null;
                            /** Format: uuid */
                            suppressedBy: string | null;
                            title: string;
                            variantKey: string;
                            /** Format: uuid */
                            versionId: string;
                            what: components["schemas"]["What"];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RulebookInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulebook/explain/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulebook/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            edges: {
                                source: string;
                                target: string;
                                type: string;
                            }[];
                            nodes: {
                                data: {
                                    [key: string]: unknown;
                                };
                                id: string;
                                label: string;
                                type: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulebook/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["RuleListItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionDetail"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvaluateBodyInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            advisory: boolean;
                            /** Format: uuid */
                            evaluationId: string;
                        };
                    };
                };
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            advisory: boolean;
                            /** @enum {string|null} */
                            evaluationId: null;
                            /** @enum {string} */
                            job: "check";
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["EvaluationListItem"][];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Campaign: {
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRef"];
            /** Format: uuid */
            id: string;
            latestVersionState: ("draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired") | null;
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
        };
        CampaignDetail: {
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRef"];
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
            versions: components["schemas"]["VersionSummary"][];
        };
        CampaignDetailInput: {
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRefInput"];
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
            versions: components["schemas"]["VersionSummaryInput"][];
        };
        CampaignInput: {
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRefInput"];
            /** Format: uuid */
            id: string;
            latestVersionState: ("draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired") | null;
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
        };
        CampaignListItem: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            latestVersion: components["schemas"]["VersionSummary"] | null;
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
        };
        CampaignListItemInput: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            latestVersion: components["schemas"]["VersionSummaryInput"] | null;
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
        };
        Citation: {
            /** @enum {string} */
            confidence: "PRIMARY" | "SECONDARY" | "DERIVED" | "PLATFORM" | "UNVERIFIED";
            graphNodeId: string;
            instrument: string;
            title: string;
            url?: string;
        };
        CitationInput: {
            /** @enum {string} */
            confidence: "PRIMARY" | "SECONDARY" | "DERIVED" | "PLATFORM" | "UNVERIFIED";
            graphNodeId: string;
            instrument: string;
            title: string;
            url?: string;
        };
        Classification: {
            advisory?: {
                /** @enum {string} */
                classification: "promotional" | "service" | "mixed" | "unknown";
                confidence: number;
                model: string;
                promptVersion: string;
                provider: string;
                rationale: string;
            };
            /** @enum {string} */
            classification: "promotional" | "service" | "mixed" | "unknown";
            /** @enum {string} */
            confidence: "high" | "low";
            /** @enum {string} */
            evaluateAs: "promotional" | "service";
            promotionalMarkers: string[];
            reason: string;
            serviceMarkers: string[];
        };
        ClassificationInput: {
            advisory?: {
                /** @enum {string} */
                classification: "promotional" | "service" | "mixed" | "unknown";
                confidence: number;
                model: string;
                promptVersion: string;
                provider: string;
                rationale: string;
            };
            /** @enum {string} */
            classification: "promotional" | "service" | "mixed" | "unknown";
            /** @enum {string} */
            confidence: "high" | "low";
            /** @enum {string} */
            evaluateAs: "promotional" | "service";
            promotionalMarkers: string[];
            reason: string;
            serviceMarkers: string[];
        };
        Coverage: {
            applicable: number;
            cannotEvaluate: {
                missing: string[];
                reason: string;
                ruleId: string;
                title: string;
            }[];
            evaluated: number;
            notApplicable: {
                reason?: string;
                ruleId: string;
                title: string;
            }[];
            rulesInBook: number;
            statement: string;
        };
        CoverageInput: {
            applicable: number;
            cannotEvaluate: {
                missing: string[];
                reason: string;
                ruleId: string;
                title: string;
            }[];
            evaluated: number;
            notApplicable: {
                reason?: string;
                ruleId: string;
                title: string;
            }[];
            rulesInBook: number;
            statement: string;
        };
        CreateCampaignBody: {
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
        };
        CreateCampaignBodyInput: {
            /** @enum {string} */
            mode: "live" | "shadow";
            name: string;
        };
        CreateVersionBody: {
            audience: {
                mapping?: {
                    [key: string]: unknown;
                };
                /** Format: uuid */
                uploadId: string;
            } | {
                rows: {
                    [key: string]: string;
                }[];
            };
            borrowerSegment?: string;
            /** @enum {string} */
            channel: "whatsapp" | "sms" | "email" | "voice" | "visit";
            message: string;
            /** Format: uuid */
            parentVersionId?: string;
            product?: string;
            /** @enum {string} */
            purpose?: "collections" | "promotional" | "service";
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            sendWindowEnd?: string;
            /** Format: date-time */
            sentAt?: string;
            template?: components["schemas"]["Template"];
        };
        CreateVersionBodyInput: {
            audience: {
                mapping?: {
                    [key: string]: unknown;
                };
                /** Format: uuid */
                uploadId: string;
            } | {
                rows: {
                    [key: string]: string;
                }[];
            };
            borrowerSegment?: string;
            /** @enum {string} */
            channel: "whatsapp" | "sms" | "email" | "voice" | "visit";
            message: string;
            /** Format: uuid */
            parentVersionId?: string;
            product?: string;
            /** @enum {string} */
            purpose?: "collections" | "promotional" | "service";
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            sendWindowEnd?: string;
            /** Format: date-time */
            sentAt?: string;
            template?: components["schemas"]["TemplateInput"];
        };
        CreateVersionResponse: {
            jobs: "resolve"[];
            version: components["schemas"]["VersionSummary"];
        };
        CreateVersionResponseInput: {
            jobs: "resolve"[];
            version: components["schemas"]["VersionSummaryInput"];
        };
        Decision: {
            actor: components["schemas"]["UserRef"];
            /** Format: date-time */
            createdAt: string;
            expiresAt: string | null;
            /** Format: uuid */
            findingId: string;
            /** Format: uuid */
            id: string;
            reasonCode: string;
            reasonText: string;
            resultingVersionId: string | null;
            /** @enum {string} */
            scope: "this-finding" | "this-campaign" | "this-rule-30d";
            staleEvaluation: boolean;
            /** @enum {string} */
            type: "accept" | "fix" | "abandon";
            /** Format: uuid */
            versionId: string;
        };
        DecisionInput: {
            actor: components["schemas"]["UserRefInput"];
            /** Format: date-time */
            createdAt: string;
            expiresAt: string | null;
            /** Format: uuid */
            findingId: string;
            /** Format: uuid */
            id: string;
            reasonCode: string;
            reasonText: string;
            resultingVersionId: string | null;
            /** @enum {string} */
            scope: "this-finding" | "this-campaign" | "this-rule-30d";
            staleEvaluation: boolean;
            /** @enum {string} */
            type: "accept" | "fix" | "abandon";
            /** Format: uuid */
            versionId: string;
        };
        EvaluateBody: {
            /** Format: date-time */
            asOf?: string;
        };
        EvaluateBodyInput: {
            /** Format: date-time */
            asOf?: string;
        };
        EvaluationDetail: {
            advisory: boolean;
            /** Format: date-time */
            asOf: string;
            classification: components["schemas"]["Classification"];
            coverage: components["schemas"]["Coverage"];
            /** Format: date-time */
            createdAt: string;
            durationMs: number;
            /** @enum {string} */
            effectivePurpose: "collections" | "promotional" | "service";
            engineVersion: string;
            findings: components["schemas"]["Finding"][];
            /** Format: uuid */
            id: string;
            rulebookHash: string;
            rulePackIds: string[];
            summary: components["schemas"]["Summary"];
            /** Format: uuid */
            versionId: string;
        };
        EvaluationDetailInput: {
            advisory: boolean;
            /** Format: date-time */
            asOf: string;
            classification: components["schemas"]["ClassificationInput"];
            coverage: components["schemas"]["CoverageInput"];
            /** Format: date-time */
            createdAt: string;
            durationMs: number;
            /** @enum {string} */
            effectivePurpose: "collections" | "promotional" | "service";
            engineVersion: string;
            findings: components["schemas"]["FindingInput"][];
            /** Format: uuid */
            id: string;
            rulebookHash: string;
            rulePackIds: string[];
            summary: components["schemas"]["SummaryInput"];
            /** Format: uuid */
            versionId: string;
        };
        EvaluationListItem: {
            advisory: boolean;
            /** Format: date-time */
            asOf: string;
            /** Format: date-time */
            createdAt: string;
            exceptionsHash: string;
            /** Format: uuid */
            id: string;
            rulebookHash: string;
            summary: components["schemas"]["Summary"];
        };
        EvaluationListItemInput: {
            advisory: boolean;
            /** Format: date-time */
            asOf: string;
            /** Format: date-time */
            createdAt: string;
            exceptionsHash: string;
            /** Format: uuid */
            id: string;
            rulebookHash: string;
            summary: components["schemas"]["SummaryInput"];
        };
        Finding: {
            affectedCount: number;
            affectedRowsTruncated: boolean;
            affectedSample: string[];
            /** @enum {string} */
            category: "timing" | "consent" | "audience" | "content" | "identity" | "delivery";
            citation: components["schemas"]["Citation"];
            decisions: components["schemas"]["Decision"][];
            /** Format: uuid */
            evaluationId: string;
            explanation: string;
            /** Format: uuid */
            id: string;
            ruleId: string;
            /** @enum {string} */
            severity: "block" | "warn" | "info";
            suggestedFix: components["schemas"]["SuggestedFix"] | null;
            suppressedBy: string | null;
            title: string;
            variantKey: string;
            what: components["schemas"]["What"];
        };
        FindingInput: {
            affectedCount: number;
            affectedRowsTruncated: boolean;
            affectedSample: string[];
            /** @enum {string} */
            category: "timing" | "consent" | "audience" | "content" | "identity" | "delivery";
            citation: components["schemas"]["CitationInput"];
            decisions: components["schemas"]["DecisionInput"][];
            /** Format: uuid */
            evaluationId: string;
            explanation: string;
            /** Format: uuid */
            id: string;
            ruleId: string;
            /** @enum {string} */
            severity: "block" | "warn" | "info";
            suggestedFix: components["schemas"]["SuggestedFixInput"] | null;
            suppressedBy: string | null;
            title: string;
            variantKey: string;
            what: components["schemas"]["WhatInput"];
        };
        Health: {
            /** @enum {string} */
            db: "ok" | "down";
            ok: boolean;
            /** @enum {string} */
            queue: "ok" | "down";
            rulebookHash: string;
            version: string;
        };
        HealthInput: {
            /** @enum {string} */
            db: "ok" | "down";
            ok: boolean;
            /** @enum {string} */
            queue: "ok" | "down";
            rulebookHash: string;
            version: string;
        };
        LoginBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginBodyInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        Me: {
            mockConnectors: boolean;
            sealingFrozen: boolean;
            tenant: {
                entityType: string;
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
            };
            user: components["schemas"]["UserRef"];
        };
        MeInput: {
            mockConnectors: boolean;
            sealingFrozen: boolean;
            tenant: {
                entityType: string;
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
            };
            user: components["schemas"]["UserRefInput"];
        };
        Problem: {
            data?: {
                [key: string]: unknown;
            };
            detail?: string;
            instance: string;
            issues?: {
                message: string;
                path: string;
            }[];
            requestId: string;
            status: number;
            title: string;
            type: string;
        };
        ProblemInput: {
            data?: {
                [key: string]: unknown;
            };
            detail?: string;
            instance: string;
            issues?: {
                message: string;
                path: string;
            }[];
            requestId: string;
            status: number;
            title: string;
            type: string;
        };
        RulebookInfo: {
            gitRef: string | null;
            graphHash: string;
            hash: string;
            /** Format: date-time */
            loadedAt: string;
            packs: {
                id: string;
                ruleCount: number;
                sourceHash: string;
                version: string;
            }[];
        };
        RulebookInfoInput: {
            gitRef: string | null;
            graphHash: string;
            hash: string;
            /** Format: date-time */
            loadedAt: string;
            packs: {
                id: string;
                ruleCount: number;
                sourceHash: string;
                version: string;
            }[];
        };
        RuleListItem: {
            category: string | null;
            citation: {
                confidence: string;
                graphNodeId: string;
                instrument: string;
                title: string;
                url?: string;
            };
            effectiveFrom: string | null;
            id: string;
            layer: string;
            pack: string;
            requires: string[];
            sendTimeCheck: boolean;
            severity: string;
            severityBefore: string | null;
            tier: number | null;
            title: string;
        };
        RuleListItemInput: {
            category: string | null;
            citation: {
                confidence: string;
                graphNodeId: string;
                instrument: string;
                title: string;
                url?: string;
            };
            effectiveFrom: string | null;
            id: string;
            layer: string;
            pack: string;
            requires: string[];
            sendTimeCheck: boolean;
            severity: string;
            severityBefore: string | null;
            tier: number | null;
            title: string;
        };
        SuggestedFix: {
            /** @enum {string} */
            kind: "reschedule" | "drop_rows" | "edit_message" | "set_config" | "add_disclosure";
            label: string;
            payload: {
                [key: string]: unknown;
            };
        };
        SuggestedFixInput: {
            /** @enum {string} */
            kind: "reschedule" | "drop_rows" | "edit_message" | "set_config" | "add_disclosure";
            label: string;
            payload: {
                [key: string]: unknown;
            };
        };
        Summary: {
            audienceSize: number;
            blockers: number;
            cannotEvaluate: number;
            info: number;
            verdict: null;
            warnings: number;
        };
        SummaryInput: {
            audienceSize: number;
            blockers: number;
            cannotEvaluate: number;
            info: number;
            verdict: null;
            warnings: number;
        };
        Template: {
            body: string;
            category?: ("MARKETING" | "UTILITY" | "AUTHENTICATION") | null;
            externalId?: string | null;
            variables: string[];
        };
        TemplateInput: {
            body: string;
            category?: ("MARKETING" | "UTILITY" | "AUTHENTICATION") | null;
            externalId?: string | null;
            variables: string[];
        };
        UserRef: {
            displayName: string;
            /** Format: uuid */
            id: string;
            roles: ("admin" | "operator" | "reviewer" | "approver")[];
        };
        UserRefInput: {
            displayName: string;
            /** Format: uuid */
            id: string;
            roles: ("admin" | "operator" | "reviewer" | "approver")[];
        };
        VersionDetail: {
            audience: {
                consent: {
                    absent: number;
                    denied: number;
                    granted: number;
                    unknown: number;
                };
                duplicates: number;
                size: number;
                unresolvable: number;
            };
            audienceSize: number;
            borrowerSegment: string | null;
            /** Format: uuid */
            campaignId: string;
            /** @enum {string} */
            campaignMode: "live" | "shadow";
            campaignName: string;
            /** @enum {string} */
            channel: "whatsapp" | "sms" | "email" | "voice" | "visit";
            configDrift: boolean;
            configSnapshot: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRef"];
            evidence: {
                hash: string;
                /** Format: uuid */
                id: string;
                seq: number;
            } | null;
            /** Format: uuid */
            id: string;
            lastError: string | null;
            latestEvaluation: {
                /** Format: date-time */
                asOf: string;
                /** Format: uuid */
                id: string;
                rulebookHash: string;
                summary: components["schemas"]["Summary"];
            } | null;
            message: string;
            noChange: boolean;
            parentVersionId: string | null;
            product: string | null;
            progressPct: number | null;
            purpose: ("collections" | "promotional" | "service") | null;
            queuePosition: number | null;
            review: unknown | null;
            /** Format: date-time */
            scheduledAt: string;
            sendWindowEnd: string | null;
            sentAt: string | null;
            /** @enum {string} */
            state: "draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired";
            /** Format: date-time */
            stateChangedAt: string;
            supersededBy: string[];
            template: components["schemas"]["Template"] | null;
            versionNo: number;
        };
        VersionDetailInput: {
            audience: {
                consent: {
                    absent: number;
                    denied: number;
                    granted: number;
                    unknown: number;
                };
                duplicates: number;
                size: number;
                unresolvable: number;
            };
            audienceSize: number;
            borrowerSegment: string | null;
            /** Format: uuid */
            campaignId: string;
            /** @enum {string} */
            campaignMode: "live" | "shadow";
            campaignName: string;
            /** @enum {string} */
            channel: "whatsapp" | "sms" | "email" | "voice" | "visit";
            configDrift: boolean;
            configSnapshot: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRefInput"];
            evidence: {
                hash: string;
                /** Format: uuid */
                id: string;
                seq: number;
            } | null;
            /** Format: uuid */
            id: string;
            lastError: string | null;
            latestEvaluation: {
                /** Format: date-time */
                asOf: string;
                /** Format: uuid */
                id: string;
                rulebookHash: string;
                summary: components["schemas"]["SummaryInput"];
            } | null;
            message: string;
            noChange: boolean;
            parentVersionId: string | null;
            product: string | null;
            progressPct: number | null;
            purpose: ("collections" | "promotional" | "service") | null;
            queuePosition: number | null;
            review: unknown | null;
            /** Format: date-time */
            scheduledAt: string;
            sendWindowEnd: string | null;
            sentAt: string | null;
            /** @enum {string} */
            state: "draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired";
            /** Format: date-time */
            stateChangedAt: string;
            supersededBy: string[];
            template: components["schemas"]["TemplateInput"] | null;
            versionNo: number;
        };
        VersionSummary: {
            audienceSize: number;
            borrowerSegment: string | null;
            /** Format: uuid */
            campaignId: string;
            /** @enum {string} */
            channel: "whatsapp" | "sms" | "email" | "voice" | "visit";
            configDrift: boolean;
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRef"];
            /** Format: uuid */
            id: string;
            latestEvaluation: {
                /** Format: date-time */
                asOf: string;
                /** Format: uuid */
                id: string;
                rulebookHash: string;
                summary: components["schemas"]["Summary"];
            } | null;
            noChange: boolean;
            parentVersionId: string | null;
            product: string | null;
            progressPct: number | null;
            purpose: ("collections" | "promotional" | "service") | null;
            queuePosition: number | null;
            /** Format: date-time */
            scheduledAt: string;
            sendWindowEnd: string | null;
            sentAt: string | null;
            /** @enum {string} */
            state: "draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired";
            /** Format: date-time */
            stateChangedAt: string;
            supersededBy: string[];
            versionNo: number;
        };
        VersionSummaryInput: {
            audienceSize: number;
            borrowerSegment: string | null;
            /** Format: uuid */
            campaignId: string;
            /** @enum {string} */
            channel: "whatsapp" | "sms" | "email" | "voice" | "visit";
            configDrift: boolean;
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRefInput"];
            /** Format: uuid */
            id: string;
            latestEvaluation: {
                /** Format: date-time */
                asOf: string;
                /** Format: uuid */
                id: string;
                rulebookHash: string;
                summary: components["schemas"]["SummaryInput"];
            } | null;
            noChange: boolean;
            parentVersionId: string | null;
            product: string | null;
            progressPct: number | null;
            purpose: ("collections" | "promotional" | "service") | null;
            queuePosition: number | null;
            /** Format: date-time */
            scheduledAt: string;
            sendWindowEnd: string | null;
            sentAt: string | null;
            /** @enum {string} */
            state: "draft" | "resolving" | "evaluated" | "in_review" | "approved" | "rejected" | "sealed" | "handed_off" | "abandoned" | "expired";
            /** Format: date-time */
            stateChangedAt: string;
            supersededBy: string[];
            versionNo: number;
        };
        What: {
            excerpt?: string;
            field?: string;
            /** @enum {string} */
            kind: "schedule" | "message_text" | "rows" | "config" | "template";
        };
        WhatInput: {
            excerpt?: string;
            field?: string;
            /** @enum {string} */
            kind: "schedule" | "message_text" | "rows" | "config" | "template";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCampaign = components['schemas']['Campaign'];
export type SchemaCampaignDetail = components['schemas']['CampaignDetail'];
export type SchemaCampaignDetailInput = components['schemas']['CampaignDetailInput'];
export type SchemaCampaignInput = components['schemas']['CampaignInput'];
export type SchemaCampaignListItem = components['schemas']['CampaignListItem'];
export type SchemaCampaignListItemInput = components['schemas']['CampaignListItemInput'];
export type SchemaCitation = components['schemas']['Citation'];
export type SchemaCitationInput = components['schemas']['CitationInput'];
export type SchemaClassification = components['schemas']['Classification'];
export type SchemaClassificationInput = components['schemas']['ClassificationInput'];
export type SchemaCoverage = components['schemas']['Coverage'];
export type SchemaCoverageInput = components['schemas']['CoverageInput'];
export type SchemaCreateCampaignBody = components['schemas']['CreateCampaignBody'];
export type SchemaCreateCampaignBodyInput = components['schemas']['CreateCampaignBodyInput'];
export type SchemaCreateVersionBody = components['schemas']['CreateVersionBody'];
export type SchemaCreateVersionBodyInput = components['schemas']['CreateVersionBodyInput'];
export type SchemaCreateVersionResponse = components['schemas']['CreateVersionResponse'];
export type SchemaCreateVersionResponseInput = components['schemas']['CreateVersionResponseInput'];
export type SchemaDecision = components['schemas']['Decision'];
export type SchemaDecisionInput = components['schemas']['DecisionInput'];
export type SchemaEvaluateBody = components['schemas']['EvaluateBody'];
export type SchemaEvaluateBodyInput = components['schemas']['EvaluateBodyInput'];
export type SchemaEvaluationDetail = components['schemas']['EvaluationDetail'];
export type SchemaEvaluationDetailInput = components['schemas']['EvaluationDetailInput'];
export type SchemaEvaluationListItem = components['schemas']['EvaluationListItem'];
export type SchemaEvaluationListItemInput = components['schemas']['EvaluationListItemInput'];
export type SchemaFinding = components['schemas']['Finding'];
export type SchemaFindingInput = components['schemas']['FindingInput'];
export type SchemaHealth = components['schemas']['Health'];
export type SchemaHealthInput = components['schemas']['HealthInput'];
export type SchemaLoginBody = components['schemas']['LoginBody'];
export type SchemaLoginBodyInput = components['schemas']['LoginBodyInput'];
export type SchemaMe = components['schemas']['Me'];
export type SchemaMeInput = components['schemas']['MeInput'];
export type SchemaProblem = components['schemas']['Problem'];
export type SchemaProblemInput = components['schemas']['ProblemInput'];
export type SchemaRulebookInfo = components['schemas']['RulebookInfo'];
export type SchemaRulebookInfoInput = components['schemas']['RulebookInfoInput'];
export type SchemaRuleListItem = components['schemas']['RuleListItem'];
export type SchemaRuleListItemInput = components['schemas']['RuleListItemInput'];
export type SchemaSuggestedFix = components['schemas']['SuggestedFix'];
export type SchemaSuggestedFixInput = components['schemas']['SuggestedFixInput'];
export type SchemaSummary = components['schemas']['Summary'];
export type SchemaSummaryInput = components['schemas']['SummaryInput'];
export type SchemaTemplate = components['schemas']['Template'];
export type SchemaTemplateInput = components['schemas']['TemplateInput'];
export type SchemaUserRef = components['schemas']['UserRef'];
export type SchemaUserRefInput = components['schemas']['UserRefInput'];
export type SchemaVersionDetail = components['schemas']['VersionDetail'];
export type SchemaVersionDetailInput = components['schemas']['VersionDetailInput'];
export type SchemaVersionSummary = components['schemas']['VersionSummary'];
export type SchemaVersionSummaryInput = components['schemas']['VersionSummaryInput'];
export type SchemaWhat = components['schemas']['What'];
export type SchemaWhatInput = components['schemas']['WhatInput'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
