// RulePack.sourceHash (16 §2.2): sha256 of the compiled rule sources, concatenated in filename order.
// This script is the single implementation; apps/api recomputes the same way at boot (SOURCE_HASH_INPUT_GLOBS).
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist', 'src');

export function hashDir(dir) {
  const files = readdirSync(dir).filter((f) => f.endsWith('.js')).sort();
  const h = createHash('sha256');
  for (const f of files) {
    h.update(`--- ${f}\n`);
    h.update(readFileSync(join(dir, f)));
  }
  return h.digest('hex');
}

const hashes = {
  'india-layer-a': hashDir(join(dist, 'rules')),
  'preflight-hygiene': hashDir(join(dist, 'hygiene')),
};
writeFileSync(
  join(dist, 'sourceHash.js'),
  `// generated by scripts/hash-sources.mjs — do not edit\nexport const sourceHash = ${JSON.stringify(hashes, null, 2)};\n`,
);
console.log('sourceHash', hashes);
